# Question

Will the code work? Why or why not?

```js
const getUsers = async () => {
  const url = 'https://jsonplaceholder.typicode.com/users';
  const users = await fetch(url).then(r => r.json()).catch((err) => []);
  console.log(users)
  return users;
}
getUsers()
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer

Should work since the variable `users` is `await`ing both the fetch and `r.json()`; then catching whatever error may pop up and displays an empty array. 


# Teacher Feedback